# Generated by Django 5.0.3 on 2024-05-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('persona_funcion', models.CharField(max_length=75)),
                ('contenido', models.TextField(max_length=360, verbose_name='Contenido:')),
                ('imagen', models.ImageField(upload_to='servicios_media')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
